ifeq ($(shell uname), Darwin)                 # -*- makefile -*-
  metadir=$(HOME)/r/metaocaml-ppc/bin
  heap=ppc-darwin
else
  metadir=$(HOME)/r/metaocaml/bin
  heap=x86-linux
endif

sml=$(HOME)/tmp/nj45/bin/sml
ocaml=$(metadir)/metaocaml $(mlflags) $(addsuffix .cma, $(libs))
ocamlc=$(metadir)/ocamlc -thread -g

libs=unix str nums threads server
mlflags+=-I +threads

%.cma:
	$(ocamlc) -a -o $@ $^

%.cmi: %.mli
	$(ocamlc) -c $<

%.cmo: %.ml
	$(ocamlc) -c $<

junk=*.cm? *~
texjunk=aux bbl blg brf dvi log out ps waux

figs=power static browse test
figs_tex=$(addsuffix .tex, $(figs))
figs_eps=$(addsuffix .eps, $(figs))
figs_pdf=$(addsuffix .pdf, $(figs))

static-sizes=01 02 04 08 16 32 64
power-cases=17 127 255 511 1023 2047 4095 8191
dir-sizes=02 04 08 16 32 64
browse-dirs=./top server/server
