#! /bin/sh
# Usage: ./static-overhead method size 
# where method is one of:
#   apache
#   camlfile
#   camlcode

case $1 in
    caml*)
        set -m
        make -C.. run &
        sleep 4
        ;;
esac

echo '========================================' $1-$2

case $1 in
    apache)
        url=http://localhost/static$2.meta
        ;;
    php)
        url=http://localhost/static$2.php
        ;;
    camlfile)
        url=http://localhost:8000/scripts/static$2.meta
        ;;
    camlcode)
        url=http://localhost:8000/static$2
        ;;
esac

ab -k -t 30 -c 8 $url 

case $1 in
    caml*)
        kill -INT %%
        ;;
esac
